### ISSUE TITLE
Designed Enhancer Eval

### ISSUE THREAD

**Issue by wconnell** [wconnell/genplasmid#6]
### Objectives
- Methods for evaluating gene/protein variant expression as a function of designed enhancers.

### Tasks
Salis Lab Tools
- [ ] Install and configure Promoter Calculator, RBS Calculator, and CDS Calculator

Gene Expression Models
- [ ] Set up models like Enformer, chromBPNet, DeepSEA, and GENESIS.

Run test cases to verify setup
- [ ] Compare to (1) standard enhancers and (2) random sequences
